FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.15-build


RUN apk update && \
    apk add --no-cache \
    --virtual .build-deps \
    build-base \
    dbus-dev \
    glib-dev \
    python3 \
    python3-dev \
    py3-pip \
    py3-wheel \
    py3-setuptools \
    cmake \
    automake
RUN pip3 install --no-cache-dir mdns-publisher
RUN apk del .build-deps

COPY start.sh start.sh

CMD ["sh","start.sh"]
