# build tohora from source
FROM balenalib/%%BALENA_MACHINE_NAME%%-golang as builder
RUN go install github.com/mozz100/tohora@latest

FROM balenablocks/browser:%%BALENA_MACHINE_NAME%%
RUN install_packages cec-utils
COPY --from=builder /go/bin/tohora /home/chromium/tohora
COPY launch.sh /home/chromium/

# replace command that runs in start script
COPY alt_start.sh /usr/src/app/
RUN sed -i '$d' /usr/src/app/start.sh
RUN echo ". alt_start.sh"  >> /usr/src/app/start.sh